services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: docker-postgres
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - docker-postgres:/var/lib/postgresql/data
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true

volumes:
  docker-postgres:
